.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.34.2 */

glabel write
    /* 3C88 80013488 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 3C8C 8001348C 08004001 */  jr         $t2
    /* 3C90 80013490 35000924 */   addiu     $t1, $zero, 0x35
.size write, . - write
    /* 3C94 80013494 00000000 */  nop
