.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.34.2 */

glabel SetMem
    /* 2F68 80012768 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 2F6C 8001276C 08004001 */  jr         $t2
    /* 2F70 80012770 9F000924 */   addiu     $t1, $zero, 0x9F
.size SetMem, . - SetMem
    /* 2F74 80012774 00000000 */  nop
