name: LSD Dream Emulator
sha1: 76322eeade5ebb22dca57fdeac7d68c30f06308d
options:
  basename: SLPS01556
  platform: psx
  compiler: GCC

  base_path: ..
  target_path: rom/SLPS_015.56
  asm_path:    asm/
  asset_path:  assets/
  src_path:    src/

  symbol_addrs_path:           config/symbols.txt
  undefined_funcs_auto_path:   build/undefined_funcs_auto.txt
  undefined_syms_auto_path:    build/undefined_syms_auto.txt
  ld_script_path: build/SLPS01556.ld

  find_file_boundaries: False
  pair_rodata_to_text: False
  migrate_rodata_to_functions: True
  hasm_in_src_path: True
  gp_value: 0x8008A808

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, rodata]
      - [0xA8C, .rodata, memory]
      - [0xABC, rodata]
      - [0xF28, rodata]
      - [0xFA4, .rodata, game_flow]
      - [0xFD8, rodata] # 179d8
      - [0x1764, rodata]
      - [0x17EC, rodata] # 2A0E0
      - [0x1818, rodata]
      - [0x1890, rodata]
      - [0x19DC, rodata]
      - [0x1A90, rodata]
      - [0x1B84, .rodata, utils/path_helper]
      - [0x1BEC, .rodata, dream_context]
      - [0x1C08, rodata]
      - [0x1C0C, rodata]
      - [0x1C34, .rodata, main_menu]
      - [0x1D0C, rodata]
      - [0x1E28, rodata]
      - [0x1EF4, rodata]
      - [0x1F6C, .rodata, 48768]
      - [0x1F88, rodata] # DreamSys
      - [0x2048, rodata]
      - [0x206C, rodata] # greyman
      - [0x20DC, c, main]
      - [0x2258, asm, psyq_2258]
      - [0x2F68, hasm, psx/SetMem]
      - [0x2F78, c, psx/memory]
      - [0x3038, asm, psyq_libgs_matrix]
      - [0x3420, asm, psyq_libc_printf]
      - [0x345C, asm, psyq_libc_prnt]
      - [0x3AF8, asm, psyq_libc_memchr]
      - [0x3B48, asm, psyq_libc_strlen]
      - [0x3B78, asm, psyq_libc_ctype]
      - [0x3BE0, asm, psyq_libc_putchar]
      - [0x3C88, asm, psyq_libapi_write]
      - [0x3C98, asm, psyq_libgs_134]
      - [0x3F6C, asm, psyq_libgs_127]
      - [0x3FEC, asm, psyq_libgs_13]
      - [0x4004, asm, psyq_libgs_2d_sp0]
      - [0x4500, asm, psyq_libgs_2d_com1]
      - [0x4594, asm, psyq_libgs_2d_bg0]
      - [0x4D8C, asm, psyq_libgs_119]
      - [0x4E44, asm, psyq_libgs_120]
      - [0x4F68, asm, psyq_libgs_135]
      - [0x5288, asm, psyq_libgs_box0]
      - [0x5360, asm, psyq_libgs_com0]
      - [0x58D0, asm, psyq_libgte_mtx003]
      - [0x5A30, asm, psyq_libgte_mtx0]
      - [0x5B3C, asm, psyq_libgte_mtx2]
      - [0x5C20, asm, psyq_libgte_mtx1]
      - [0x5D08, asm, psyq_libgte_mtxb]
      - [0x5E18, asm, psyq_libgte_mtx4]
      - [0x5F78, asm, psyq_libgte_mtx5]
      - [0x5FA8, asm, psyq_libgte_mtxa]
      - [0x60CC, asm, psyq_libgte_mtx6]
      - [0x620C, asm, psyq_libgte_mtx9]
      - [0x6254, asm, psyq_libgte_mtx7]
      - [0x629C, asm, psyq_libgte_mtx8]
      - [0x62F0, asm, psyq_libgte_mtx03]
      - [0x63FC, asm, psyq_libgte_mtx04]
      - [0x6508, asm, psyq_libgte_mtx05]
      - [0x6558, asm, psyq_libgte_mtx06]
      - [0x65B4, asm, psyq_libgte_mtx07]
      - [0x65D8, asm, psyq_libgte_mtx08]
      - [0x66FC, asm, psyq_libgte_mtx09]
      - [0x672C, asm, psyq_libgte_mtx10]
      - [0x675C, asm, psyq_libgte_mtx11]
      - [0x678C, asm, psyq_libgte_mtx12]
      - [0x67B0, asm, psyq_libgte_cmb0]
      - [0x6830, asm, psyq_libgte_reg04]
      - [0x6844, asm, psyq_libgte_reg05]
      - [0x685C, asm, psyq_libgte_reg06]
      - [0x6870, asm, psyq_libgte_reg07]
      - [0x6884, asm, psyq_libgte_reg08]
      - [0x68A4, asm, psyq_libgte_reg09]
      - [0x68B0, asm, psyq_libgte_fgo01]
      - [0x6B40, asm, psyq_libgte_geo]
      - [0x740C, asm, psyq_libgte_geo00]
      - [0x7598, asm, psyq_libgte_geo02]
      - [0x7A10, asm, psyq_libgte_geo03]
      - [0x7D70, asm, psyq_libgte_msc02]
      - [0x7E6C, asm, psyq_unk1]
      - [0x8010, asm, psyq_libgte_smp00]
      - [0x8220, c, memory]
      - [0x86b0, c, base_class]
      - [0x8bdc, asm]
      - [0x8c64, asm, psyq_unk2]
      - [0xAD64, asm, psyq_libgte_divf3a]
      - [0xB0D4, asm, psyq_libgte_divf4a]
      - [0xB554, asm, psyq_libgte_divg3a]
      - [0xB964, asm, psyq_libgte_divg4a]
      - [0xBEB4, asm, psyq_libgte_divft3a]
      - [0xC2B4, asm, psyq_libgte_divft4a]
      - [0xC7D4, asm, psyq_libgte_divgt3a]
      - [0xCC74, asm, psyq_libgte_divgt4a]
      - [0xD294, c]
      - [0xED8C, asm]
      - [0xF770, asm, psyq_libgs_objt]
      - [0xF8C8, asm, psyq_libgte_ratan]
      - [0xFA50, c]
      - [0xFB94, asm]
      - [0x10EE0, c, gs_helper]
      - [0x1145C, asm]
      - [0x154E0, asm, psyq_libetc_intr]
      - [0x15D04, asm, psyq_libetc_vmode]
      - [0x15D2C, asm, psyq_libetc_intr_dma]
      - [0x15FD4, asm, psyq_libetc_intr_vb]
      - [0x16100, asm, psyq_libetc_vsync]
      - [0x16334, c]
      - [0x166ac, asm, psyq_libetc_pad]
      - [0x1677c, c, game_flow]
      - [0x171f0, c]
      - [0x17930, asm, psyq_libc_strcat]
      - [0x179d8, asm]
      - [0x19C78, asm, psyq_libcd_bios]
      - [0x1BE40, asm, psyq_libcd_iso9660]
      - [0x1C92C, c]
      - [0x1CBB8, c]
      - [0x1CC80, c, sound_engine]
      - [0x1D41C, asm]
      - [0x272c8, asm, psyq_SpuSetMute]
      - [0x2A0E0, c]
      - [0x2A85C, asm]
      - [0x2b78c, c]
      - [0x2ba1c, asm]
      - [0x2bb9c, c, texture_helper]
      - [0x2be24, asm]
      - [0x2c054, c, asset_player]
      - [0x2c694, c]
      - [0x2e7dc, c, timer]
      - [0x2edd8, c, renderer]
      - [0x2faac, asm]
      - [0x305B0, c]
      - [0x30CD0, c]
      - [0x310CC, c]
      - [0x317C0, asm]
      - [0x3197c, asm, psyq_memset]
      - [0x322B4, c]
      - [0x3244C, asm]
      - [0x3249C, c]
      - [0x326E8, c]
      - [0x32ACC, c]
      - [0x32C00, c]
      - [0x32E94, c]
      - [0x330F4, asm, GsSetAmbient]
      - [0x3311C, c]
      - [0x3328C, asm]
      - [0x33808, c]
      - [0x34040, c]
      - [0x34388, c]
      - [0x34684, c]
      - [0x349B4, c]
      - [0x34E8C, c]
      - [0x3520C, c]
      - [0x354D4, c]
      - [0x35730, c]
      - [0x359B8, c]
      - [0x35C38, c]
      - [0x36654, asm]
      - [0x3770C, c]
      - [0x38110, asm, psyq_libcd_c002]
      - [0x38170, asm, psyq_libcd_c003]
      - [0x381C8, asm, psyq_libcd_read2]
      - [0x3825C, asm, psyq_libcd_c005]
      - [0x382E4, asm, psyq_libcd_c008]
      - [0x38324, asm, psyq_libcd_c011]
      - [0x38E5C, asm, psyq_libcd_c010]
      - [0x38E7C, asm, psyq_libcd_cdrom]
      - [0x38EAC, asm, psyq_libcd_c009]
      - [0x38FD8, asm, psyq_libcd_c007]
      - [0x39094, c]
      - [0x394F0, c, utils/path_helper]
      - [0x39c80, asm, psyq_libc_rand]
      - [0x39cb4, c, stage_grid]
      - [0x39e08, c, dream_context]
      - [0x3A930, c]
      - [0x3ACC8, c]
      - [0x3DA54, c]
      - [0x3DB8C, c]
      - [0x3DD18, c, main_menu]
      - [0x3eae0, c, memory_card]
      - [0x40ff8, asm]
      - [0x413A8, c]
      - [0x4225C, c]
      - [0x43370, c]
      - [0x44CE4, asm]
      - [0x46B20, c]
      - [0x4775C, asm]
      - [0x477E4, c]
      - [0x48494, c]
      - [0x48768, c]
      - [0x48F74, c, dream_sys]
      - [0x4CD08, asm, 4cd08] #DreamAux
      - [0x4D7DC, c, entity]
      - [0x4E960, asm]
      - [0x55DD4, c] #class
      - [0x57028, .data, main]
      - [0x57040, data]
      - [0x721CC, .data, utils/path_helper]
      - [0x769D4, .data, stage_grid]
      - [0x76A44, data]
      - [0x76DC8, data] #class_39e08
      - [0x7749C, .data, main_menu]
      - [0x775C4, data]
      - [0x783dc, data] # DreamSys
      - [0x79528, data]
      - [0x7b008, .sdata, main]
      - [0x7B00C, sdata]
      # - [0x7B018, .data, memory]
      - [0x7b018, .sdata, memory]
      - [0x7b020, sdata]
      - [0x7b04c, .sdata, 171F0]
      - [0x7b050, sdata]
      - [0x7b0d4, sdata]  #2A0E0
      - [0x7b0dc, sdata]
      - [0x7b158, .sdata, utils/path_helper]
      - [0x7B16C, sdata]
      - [0x7b184, .sdata, main_menu]
      - [0x7b230, sdata]
      - [0x7b3c0, sdata] # DreamSys
      - [0x7b3f8, sdata]
      - [0x7b420, .sbss, main]
      - [0x7b424, sbss]
      - [0x7B468, sbss] #psyq_rand
      - [0x7B46C, sbss]
      - [0x7b4b4, sbss] # DreamSys
      - [0x7b4cc, sbss]
  - [0x7B800]
