name: LSD Dream Emulator
sha1: 76322eeade5ebb22dca57fdeac7d68c30f06308d
options:
  basename: SLPS01556
  platform: psx
  compiler: GCC

  base_path: ..
  target_path: rom/SLPS_015.56
  asm_path:    asm/
  asset_path:  assets/
  src_path:    src/

  symbol_addrs_path:           config/symbols.txt
  undefined_funcs_auto_path:   build/undefined_funcs_auto.txt
  undefined_syms_auto_path:    build/undefined_syms_auto.txt
  ld_script_path: build/SLPS01556.ld

  find_file_boundaries: False
  pair_rodata_to_text: False
  migrate_rodata_to_functions: True
  hasm_in_src_path: True
  gp_value: 0x8008A808

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, rodata]
      - [0xA8C, .rodata, memory]
      - [0xABC, rodata]
      - [0xF28, rodata]
      - [0xFA4, .rodata, game_flow]
      - [0xFD8, rodata] # 179d8
      - [0x1764, rodata]
      - [0x17EC, .rodata, bgm]
      - [0x1818, rodata]
      - [0x1890, .rodata, ui_screen] # jtbl_80011090 + jtbl_800110D0
      - [0x1908, rodata] # jtbl_80011108 / strings
      - [0x19DC, rodata]
      - [0x1A90, .rodata, 3249C]
      - [0x1AA4, rodata]
      - [0x1B84, .rodata, utils/cd_paths]
      - [0x1BEC, .rodata, dream_session] # strings + jtbl_8001140C (on_link_code)
      - [0x1C34, .rodata, main_menu]
      - [0x1D0C, rodata]
      - [0x1D7C, .rodata, memory_card] # jtbl_8001157C (FBE4) + jtbl_80011594 (50034)
      - [0x1DD0, rodata] # D_800115D0 / D_80011610 / D_8001161C
      - [0x1E28, rodata]
      - [0x1EF4, .rodata, 4225C] # jtbl_800116F4 (func_800522DC)
      - [0x1F4C, .rodata, map_scene_post] # jtbl_8001174C (func_80053984)
      - [0x1F6C, .rodata, graph_screen]
      - [0x1F88, .rodata, dream_sys] # jtbl_80011788 (set_move_from_pad) + jtbl_80011848
      - [0x206C, rodata] # greyman
      - [0x20DC, c, main]
      - [0x2258, c, psyq/malloc]
      - [0x2864, c, 2864]
      - [0x2F68, hasm, psyq/SetMem]
      - [0x2F78, c, psyq/libc/memory]
      - [0x3038, c, psyq/gs/matrix]
      - [0x3420, c, psyq/libc/printf]
      - [0x345C, c, psyq/libc/prnt]
      - [0x3AF8, c, psyq/libc/memchr]
      - [0x3B48, c, psyq/libc/strlen]
      - [0x3B78, c, psyq/libc/ctype]
      - [0x3BE0, c, psyq/libc/putchar]
      - [0x3C88, hasm, psyq/write]
      - [0x3C98, c, psyq/gs/134]
      - [0x3F6C, c, psyq/gs/127]
      - [0x3FEC, c, psyq/gs/13]
      - [0x4004, c, psyq/gs/2d_sp0]
      - [0x4500, c, psyq/gs/2d_com1]
      - [0x4594, c, psyq/gs/2d_bg0]
      - [0x4D8C, c, psyq/gs/119]
      - [0x4E44, c, psyq/gs/120]
      - [0x4F68, c, psyq/gs/135]
      - [0x5288, c, psyq/gs/box0]
      - [0x5360, c, psyq/gs/com0]
      - [0x58D0, c, psyq/gte/mtx003]
      - [0x5A30, c, psyq/gte/mtx0]
      - [0x5B3C, c, psyq/gte/mtx2]
      - [0x5C20, c, psyq/gte/mtx1]
      - [0x5D08, c, psyq/gte/mtxb]
      - [0x5E18, c, psyq/gte/mtx4]
      - [0x5F78, c, psyq/gte/mtx5]
      - [0x5FA8, c, psyq/gte/mtxa]
      - [0x60CC, c, psyq/gte/mtx6]
      - [0x620C, c, psyq/gte/mtx9]
      - [0x6254, c, psyq/gte/mtx7]
      - [0x629C, c, psyq/gte/mtx8]
      - [0x62F0, c, psyq/gte/mtx03]
      - [0x63FC, c, psyq/gte/mtx04]
      - [0x6508, c, psyq/gte/mtx05]
      - [0x6558, c, psyq/gte/mtx06]
      - [0x65B4, c, psyq/gte/mtx07]
      - [0x65D8, c, psyq/gte/mtx08]
      - [0x66FC, c, psyq/gte/mtx09]
      - [0x672C, c, psyq/gte/mtx10]
      - [0x675C, c, psyq/gte/mtx11]
      - [0x678C, c, psyq/gte/mtx12]
      - [0x67B0, c, psyq/gte/cmb0]
      - [0x6830, c, psyq/gte/reg04]
      - [0x6844, c, psyq/gte/reg05]
      - [0x685C, c, psyq/gte/reg06]
      - [0x6870, c, psyq/gte/reg07]
      - [0x6884, c, psyq/gte/reg08]
      - [0x68A4, c, psyq/gte/reg09]
      - [0x68B0, c, psyq/gte/fgo01]
      - [0x6B40, c, psyq/gte/geo]
      - [0x740C, c, psyq/gte/geo00]
      - [0x7598, c, psyq/gte/geo02]
      - [0x7A10, c, psyq/gte/geo03]
      - [0x7D70, c, psyq/gte/msc02]
      - [0x8010, c, psyq/gte/smp00]
      - [0x8220, c, memory]
      - [0x86b0, c, base_class]
      - [0x8c64, asm, psyq_unk2]
      - [0xAD64, c, psyq/gte/divf3a]
      - [0xB0D4, c, psyq/gte/divf4a]
      - [0xB554, c, psyq/gte/divg3a]
      - [0xB964, c, psyq/gte/divg4a]
      - [0xBEB4, c, psyq/gte/divft3a]
      - [0xC2B4, c, psyq/gte/divft4a]
      - [0xC7D4, c, psyq/gte/divgt3a]
      - [0xCC74, c, psyq/gte/divgt4a]
      - [0xD294, c]
      - [0xED8C, c, ED8C]
      - [0xF770, c, psyq/gs/objt]
      - [0xF8C8, c, psyq/gte/ratan]
      - [0xFA50, c]
      - [0xFB94, c, FB94]
      - [0x10D48, c, psyq/gs/GsMapModelingData]
      - [0x10DC0, c, psyq/gte/SquareRoot0]
      - [0x10EE0, c, display]
      - [0x1145C, c]
      - [0x11474, c, psyq/gpu/sys]
      - [0x140DC, c, psyq/gs/001]
      - [0x14708, c, psyq/gpu/prim]
      - [0x14E9C, c, psyq/gs/003]
      - [0x14F34, c, psyq/gs/103]
      - [0x14FD4, c, psyq/gs/121]
      - [0x15020, c, psyq/gs/002]
      - [0x1514C, c, psyq/gs/010]
      - [0x15240, c, psyq/gte/reg03]
      - [0x154E0, c, psyq/etc/intr]
      - [0x15D04, c, psyq/etc/vmode]
      - [0x15D2C, c, psyq/etc/intr_dma]
      - [0x15FD4, c, psyq/etc/intr_vb]
      - [0x16100, c, psyq/etc/vsync]
      - [0x16334, c, pad]
      - [0x166ac, c, psyq/etc/pad]
      - [0x1677c, c, game_flow]
      - [0x171f0, c, file_buf]
      - [0x17930, c, psyq/libc/strcat]
      - [0x179D8, c, cd_file_driver]
      - [0x19378, c, psyq/libc/strcpy]
      - [0x193BC, c, psyq/libc/strstr]
      - [0x19434, c, psyq/cd/lib]
      - [0x1C92C, c]
      - [0x1CBB8, c, debug_file_driver]
      - [0x1CC80, c, sound]
      - [0x1D718, asm, psyq_unk3]
      - [0x20FF0, c, psyq/spu/SpuVmSetProgVol]
      - [0x21180, asm]
      - [0x221B4, c, psyq/snd/SsUtPitchBend]
      - [0x22244, asm]
      - [0x22948, c, psyq/spu/SpuVmVSetUp]
      - [0x22A1C, c, psyq/spu/S_I]
      - [0x22BA8, c, psyq/snd/SsSetTableSize]
      - [0x22D88, c]
      - [0x23498, c, psyq/snd/SsVabOpenHead]
      - [0x2397C, c, psyq/snd/SsUtGetVabHdr]
      - [0x23A60, c, psyq/snd/SsUtGetVagAtr]
      - [0x23CA0, c, psyq/snd/SsSetMVol]
      - [0x23CF0, c, psyq/snd/SsUtGetProgAtr]
      - [0x23DFC, c, psyq/snd/SsVabTransBody]
      - [0x23ECC, c, psyq/snd/SsSetMute]
      - [0x23F0C, c, psyq/snd/SsVabTransCompleted]
      - [0x23F38, c, psyq/snd/SsSeqCalledTbyT]
      - [0x241AC, c, psyq/snd/Snd_pause]
      - [0x242B0, c, psyq/snd/Snd_tempo]
      - [0x24490, c]
      - [0x247B8, c, psyq/snd/Snd_replay]
      - [0x24820, c, psyq/snd/SsVabClose]
      - [0x2490C, c]
      - [0x2673C, c, psyq/snd/_SsUtResolveADSR]
      - [0x26824, c, psyq/snd/SsUtReverbOn]
      - [0x26A30, c, psyq/snd/SsUtSetVagAtr]
      - [0x26BFC, c]
      - [0x26C10, c, psyq/snd/_SsSndNextSep]
      - [0x26D18, c]
      - [0x270E8, c, psyq/snd/Snd_stop]
      - [0x272A8, c]
      - [0x272c8, c, psyq/spu/SpuSetMute]
      - [0x2A0E0, c, bgm]
      - [0x2A878, c, psyq/snd/SsSeqSetVol]
      - [0x2A94C, c, psyq/snd/Snd_SetReplayMode]
      - [0x2AA44, c, psyq/snd/Snd_setvol_data]
      - [0x2AE70, c, psyq/snd/SsSeqOpen]
      - [0x2B268, c, psyq/snd/Snd_SetPlayMode]
      - [0x2B49C, c, psyq/snd/seq_close]
      - [0x2B660, c, psyq/snd/Snd_SetPauseMode]
      - [0x2b78c, c, system]
      - [0x2BA1C, c, psyq/gs/GsInit3D]
      - [0x2BA94, c, psyq/cd/CdInit]
      - [0x2bb9c, c, tim_image]
      - [0x2BE24, c]
      - [0x2BF70, c, psyq/gs/GsGetTimInfo]
      - [0x2c054, c, movie_screen]
      - [0x2c694, c, ui_screen]
      - [0x2e7dc, c, timer]
      - [0x2edd8, c, renderer]
      - [0x2FAAC, c, psyq/gs/GsSetRefView2]
      - [0x30048, c, psyq/gs/GsGetLw]
      - [0x3030C, c]
      - [0x303F4, c, psyq/gs/GsDrawOt]
      - [0x30418, c, psyq/gs/GsClearOt]
      - [0x30470, c, psyq/gs/GsSetLightMode]
      - [0x304FC, c, psyq/gs/TransposeMatrix]
      - [0x3054C, c, psyq/gs/SetFogNear]
      - [0x305B0, c, effect]
      - [0x30CD0, c]
      - [0x310CC, c, text_line]
      - [0x3197c, c, psyq/libc/memset]
      - [0x322B4, c]
      - [0x3249C, c]
      - [0x326E8, c]
      - [0x32ACC, c, seq_file]
      - [0x32C00, c, frame_phase]
      - [0x32E94, c]
      - [0x330F4, c, psyq/gs/110]
      - [0x3311C, c]
      - [0x3328C, c, psyq/gs/GsSetFlatLight]
      - [0x33808, c]
      - [0x34040, c, tmd_model]
      - [0x34388, c]
      - [0x34684, c]
      - [0x349B4, c]
      - [0x34E8C, c]
      - [0x3520C, c]
      - [0x354D4, c]
      - [0x35730, c]
      - [0x359B8, c]
      - [0x35C38, c, mdec_movie]
      - [0x36654, c, psyq/libpress/libpress]
      - [0x36D38, c, psyq/libc/exit]
      - [0x36DB8, c, psyq/libpress/vlc]
      - [0x3711C, c, psyq/libpress/vlc2]
      - [0x3770C, c, str_stream]
      - [0x38110, c, psyq/cd/c002]
      - [0x38170, c, psyq/cd/c003]
      - [0x381C8, c, psyq/cd/read2]
      - [0x3825C, c, psyq/cd/c005]
      - [0x382E4, c, psyq/cd/c008]
      - [0x38324, c, psyq/cd/c011]
      - [0x38E5C, c, psyq/cd/c010]
      - [0x38E7C, c, psyq/cd/cdrom]
      - [0x38EAC, c, psyq/cd/c009]
      - [0x38FD8, c, psyq/cd/c007]
      - [0x39094, c]
      - [0x394F0, c, utils/cd_paths]
      - [0x39c80, c, psyq/libc/rand]
      - [0x39cb4, c, stage_grid]
      - [0x39e08, c, dream_session]
      - [0x3a870, c, dream_session_path]
      - [0x3A930, c, scene]
      - [0x3ACC8, c]
      - [0x3DA54, c]
      - [0x3DB8C, c]
      - [0x3DD18, c, main_menu]
      - [0x3eae0, c, memory_card]
      - [0x40FF8, asm]
      - [0x41148, c, psyq/libc/atoi]
      - [0x412A4, c, psyq/libc/todigit]
      - [0x41308, c, psyq/card/c172]
      - [0x41318, c, psyq/card/c171]
      - [0x41328, c, psyq/card/card]
      - [0x41358, c, psyq/card/a78]
      - [0x41368, c, psyq/card/a74]
      - [0x41378, c, psyq/card/a75]
      - [0x41388, c, psyq/card/c112]
      - [0x41398, c, psyq/card/a80]
      - [0x413A8, c, 413A8]
      - [0x4225C, c]
      - [0x43370, c, map_scene]
      - [0x43EB0, c, map_scene_post]
      - [0x44CE4, c, 44CE4]
      - [0x46B20, c, 46B20]
      - [0x4775C, c]
      - [0x477E4, c]
      - [0x48494, c]
      - [0x48768, c, graph_screen]
      - [0x48F74, c, dream_sys]
      - [0x4CD08, c, link]
      - [0x4D7DC, c, entity]
      - [0x55DD4, c] #class
      - [0x57028, .data, main]
      - [0x57040, data]
      - [0x5BD8C, .data, base_class]
      - [0x5BDCC, data]
      - [0x5C6A0, .data, FA50]
      - [0x5C6F0, data]
      - [0x5C870, .data, display]
      - [0x5C8F8, data]
      - [0x5DBC8, .data, game_flow]
      - [0x5DC30, .data, file_buf]
      - [0x5DCE8, data]
      - [0x5E1BC, .data, debug_file_driver]
      - [0x5E234, data]
      - [0x5EC8C, .data, bgm]
      - [0x5ECF0, .data, system]
      - [0x5ED58, data]
      - [0x5EDF8, .data, movie_screen]
      - [0x5EF30, data]
      - [0x5F078, .data, timer]
      - [0x5F0E4, data]
      - [0x5F390, .data, text_line]
      - [0x5F468, data]
      - [0x5F474, .data, 322B4]
      - [0x5F540, data]
      - [0x5F54C, .data, 3249C]
      - [0x5F610, data]
      - [0x5F61C, .data, 326E8]
      - [0x5F6D8, .data, seq_file]
      - [0x5F750, .data, frame_phase]
      - [0x5F7AC, .data, 32E94]
      - [0x5F86C, .data, 3311C]
      - [0x5F8B8, data]
      - [0x5F9C4, .data, 34388]
      - [0x5FA40, data]
      - [0x5FC98, .data, 354D4]
      - [0x5FD14, .data, 35730]
      - [0x5FD90, .data, 359B8]
      - [0x5FE14, data]
      - [0x721CC, .data, utils/cd_paths]
      - [0x769D4, .data, stage_grid]
      - [0x76DC8, .data, dream_session]
      - [0x76E68, .data, scene]
      - [0x76EE8, data]
      - [0x771D8, .data, 3DA54]
      - [0x772A0, .data, 3DB8C]
      - [0x77360, .data, main_menu]
      - [0x775C4, data]
      - [0x783dc, data] # DreamSys
      - [0x79528, data]
      - [0x7A2D4, .data, entity]
      - [0x7AEC4, .data, 55DD4]
      - [0x7b008, .sdata, main]
      - [0x7B00C, sdata]
      # - [0x7B018, .data, memory]
      - [0x7b018, .sdata, memory]
      - [0x7b020, .sdata, base_class]
      - [0x7b024, sdata]
      - [0x7B03C, .sdata, 1145C]
      - [0x7B040, sdata]
      - [0x7b04c, .sdata, file_buf]
      - [0x7b058, sdata]
      - [0x7b0b0, .sdata, debug_file_driver]
      - [0x7b0b8, sdata]
      - [0x7b0d4, sdata]
      - [0x7b0d8, .sdata, bgm]
      - [0x7b0dc, .sdata, system]
      - [0x7b0e0, .sdata, screen]
      - [0x7b0e8, sdata]
      - [0x7b134, .sdata, 34388]
      - [0x7b138, sdata]
      - [0x7b158, .sdata, utils/cd_paths]
      - [0x7B16C, sdata]
      - [0x7B178, .sdata, dream_session_path]
      - [0x7B180, sdata]
      - [0x7b184, .sdata, main_menu]
      - [0x7b230, .sdata, memory_card]
      - [0x7b234, sdata]
      - [0x7b3c0, sdata] # DreamSys
      - [0x7b3f8, .sdata, link]
      - [0x7b40c, sdata]
      - [0x7b420, .sbss, main]
      - [0x7b424, sbss]
      - [0x7B468, sbss] #psyq_rand
      - [0x7B46C, sbss]
      - [0x7b4b4, sbss] # DreamSys
      - [0x7b4cc, sbss]
  - [0x7B800]
